baseURL = "https://fabio.tramasoli.com"
title = "oibaf ilosamart"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = "UA-68870540-1"

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "pt"

[params.info]
description = ""
title404 = "Eita, tem nada aqui, amigão!"

[params.assets]
favicon = "images/favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = "<a rel='license' href='http://creativecommons.org/licenses/by/4.0/'><img alt='Creative Commons License' style='border-width:0' src='https://i.creativecommons.org/l/by/4.0/88x31.png' /></a>"
holder = "Fábio Tramasoli"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006-01-02"
listDateFormat = "2006-01-02"
archiveDateFormat = "02/01"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#ffcd00"
hideMainMenu = false
rtl = false

[params.sidebar]
enable = true

[params.widgets]
header = ["breadcrumbs"]
homepage = ["recent_posts"]
sidebar = ["about", "recent_posts", "sidebar_menu", "taxonomy_cloud"]
footer = ["social_menu"]

[params.opengraph.twitter]
page = "ilosamart" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
github = "ilosamart"
gitlab = "ilosamart"
linkedin = "ilosamart"
twitter = "ilosamart"
# youtube = "UCT-U0rNerYxItGcuoPX-WYA"

[params.comments]
enable = true

# Isso: https://posativ.org/isso/
[params.comments.isso]
enable = false
scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

# Utterances: https://utteranc.es
[params.comments.utterances]
enable = true
issueTerm = "pathname" # pathname / url / title

[params.comments.utterances.github]
username = "ilosamart"
repository = "ilosamart.github.io"
label = "utteranc"

[params.search]
client = "lunr" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[blackfriday]
hrefTargetBlank = true

[languages]
[languages.pt]
lang = "pt"
languageName = "Português"
weight = 1
